apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      containers:
      - image: orgerta/ruby:v2
        name: hellok8s-container
        ports:
        - name: rubyport
          containerPort: 4567
          
 
